In [1]:
import tensorflow as tf

2024-04-08 18:27:29.381430: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-08 18:27:34.240348: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
from tensorflow import keras as keras
from keras import layers as layers

In [3]:
import os, timeit
from skimage.filters import threshold_otsu
import numpy as np
from math import inf as inf

In [4]:
import pandas as pd

In [5]:
from spectral.io import envi as envi
from spectral import imshow

In [6]:
from sklearn.decomposition import IncrementalPCA

In [7]:
import sys

In [8]:
import random

tf.random.set_seed(42)
np.random.seed(42)
random.seed(42)

In [9]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_visible_devices(physical_devices[1], 'GPU')

Num GPUs Available:  2


In [10]:
from sys import platform
DATA_DIRECTORY = ""
SLASH = ""
if platform == "linux" or platform == "linux2":
    DATA_DIRECTORY = "/home/tyagi/Desktop/wheat/data/BULK/"
    SLASH = "/"
elif platform == "win32":
    DATA_DIRECTORY = "D:\wheat\data\BULK\\"
    SLASH="\\"

In [11]:
#Constants
BAND_NUMBER = 60
FILLED_AREA_RATIO = 0.9
TRAIN_IMAGE_COUNT = 1200
VAL_IMAGE_COUNT = 400
TEST_IMAGE_COUNT = 400
NUM_VARIETIES = 4

IMAGE_WIDTH = 30
IMAGE_HEIGHT = 30

In [12]:
ACTIVATION_TYPE =  "relu"
BATCH_SIZE = 2*NUM_VARIETIES
LEARNING_RATE_BASE = 0.0001

In [13]:
from enum import Enum

class filter_method(Enum):
    none = 0
    snv = 1
    msc = 2
    savgol = 3
    
FILTER = filter_method(2).name

# to be set if filter chosen is savgol
WINDOW = 7
ORDER = 2
DERIVATIVE = "none"

In [14]:
from enum import Enum
 
class feature_extraction_method(Enum):
    none = 0
    pca_loading = 1
    lda = 2
    ipca = 3

FEATURE_EXTRACTION = feature_extraction_method(0).name

NUM_OF_BANDS = 3
if FEATURE_EXTRACTION == "pca_loading" or FEATURE_EXTRACTION == "ipca":
    NUM_OF_BANDS = 8
elif FEATURE_EXTRACTION == "lda":
    NUM_OF_BANDS = 3
    assert NUM_OF_BANDS <= min(NUM_VARIETIES-1,168),"NUM_OF_BANDS is greater."


REMOVE_NOISY_BANDS = False
FIRST_BAND = 15
LAST_BAND = 161

In [15]:
def start_timer():
    print("Testing started")
    return timeit.default_timer()

def end_timer():
    return timeit.default_timer()

def show_time(tic,toc): 
    test_time = toc - tic
    print('Testing time (s) = ' + str(test_time) + '\n')

In [16]:
# List for All varieties
VARIETIES = []
VARIETIES_CODE = {}

for name in os.listdir(DATA_DIRECTORY):
    if (name.endswith(".hdr") or name.endswith(".bil")):
        continue
    VARIETIES_CODE[name] = len(VARIETIES)
    VARIETIES.append(name)
    if len(VARIETIES)==NUM_VARIETIES:
        break

In [17]:
def dataset_file_name(variety):
    name = "./dataset/V"+str(variety).zfill(3)+"_FilledArea_"+str(FILLED_AREA_RATIO)+"_NumOfBands_"+str(NUM_OF_BANDS)+"_FB_"+str(FIRST_BAND)+"_LB_"+str(LAST_BAND)+"_BandNo_"+str(BAND_NUMBER)+"_ImageHeight_"+str(IMAGE_HEIGHT)+"_ImageWidth_"+str(IMAGE_WIDTH)+"_FILTER_"+str(FILTER)+"_FeatureExtraction_"+str(FEATURE_EXTRACTION)
    if REMOVE_NOISY_BANDS:
        name+="_REMOVE_NOISY_BANDS_"+str(REMOVE_NOISY_BANDS)
    if FILTER == "savgol":
        name+="_WINDOW_"+str(WINDOW)+"_ORDER_"+str(ORDER)
    return name

In [18]:
x_train = []
y_train = []
x_val = []
y_val = []
test_dataset=[]
test_dataset_label = []

for idx, v in enumerate(VARIETIES):
    print("idx: ",idx)
    if idx >= NUM_VARIETIES:
        break
    x_train= x_train + np.load(dataset_file_name(v)+"_train_dataset.npy").tolist()
    y_train = y_train + np.load(dataset_file_name(v)+"_train_dataset_label.npy").tolist()
    x_val= x_val + np.load(dataset_file_name(v)+"_val_dataset.npy").tolist()
    y_val = y_val + np.load(dataset_file_name(v)+"_val_dataset_label.npy").tolist()
    test_dataset = test_dataset + np.load(dataset_file_name(v)+"_test_dataset.npy").tolist()
    test_dataset_label = test_dataset_label + np.load(dataset_file_name(v)+"_test_dataset_label.npy").tolist()
    
x_train = np.array(x_train)
y_train = np.array(y_train)
x_val = np.array(x_val)
y_val = np.array(y_val)
test_dataset = np.array(test_dataset)
test_dataset_label = np.array(test_dataset_label)

idx:  0
idx:  1
idx:  2
idx:  3


In [19]:
import matplotlib.pyplot as plt
import numpy as np
import keras
import keras.backend as K
import tensorflow as tf
from keras.layers import Dropout, Input, Conv2D, MaxPooling2D, Activation, BatchNormalization, Add, Conv2DTranspose, Flatten, Dense, Conv1D, AveragePooling2D, LeakyReLU, PReLU, GlobalAveragePooling2D
from keras.layers import concatenate
from keras.models import Model

import os, pdb, timeit
import numpy as np
from keras.callbacks import TensorBoard
from keras.optimizers import Adam

from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
import matplotlib.cm as cm

In [20]:
def normalizeDataWholeSeed(data,normalization_type='max'):
    
    if normalization_type == 'max':
        for idx in range(data.shape[0]):
            data[idx,:,:,:] = data[idx,:,:,:]/np.max(abs(data[idx,:,:,:]))
            
    elif normalization_type == 'l2norm':
        from numpy import linalg as LA
        for idx in range(data.shape[0]):
            data[idx,:,:,:] = data[idx,:,:,:]/LA.norm(data[idx,:,:,:]) # L2-norm by default        
        
    return data

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [22]:
import seaborn as sn
import pandas as pd

In [23]:
def evaluate(model,dataset,dataset_label,normalization_type):
    print("--------------Make Predictions--------------")    
    x = np.array(dataset)
    labels = np.array(dataset_label)
    
    # Normalize the data
    x = normalizeDataWholeSeed(x,normalization_type=normalization_type)
    
    num = x.shape[0]

    print("Testing started")
    tic = timeit.default_timer()
    labels_predicted = model.predict(x)
    toc = timeit.default_timer()
    test_time = toc - tic
    print('Testing time (s) = ' + str(test_time) + '\n')
    
    print("--------")
    # Classification accuracy
    labels_integer_format = labels
    labels_predicted_integer_format = np.argmax(labels_predicted, axis=1)
    
    # Calculate accuracy
    accuracy = accuracy_score(labels_integer_format, labels_predicted_integer_format)
    print("Accuracy:", accuracy)
    
    # Confusion matrices
    confusion_matrix_results = confusion_matrix(labels_integer_format, labels_predicted_integer_format)
    print("Confusion matrix = ")
    print(confusion_matrix_results)
    print("------------------------------------------------")
    
    df_cm = pd.DataFrame(confusion_matrix_results,index =[i for i in VARIETIES],columns=[i for i in VARIETIES])
    sn.heatmap(df_cm, annot=True, annot_kws={"size": 16},fmt='.0f') # font size

    plt.show()

    # Calculate precision, recall, and F1-score for each class
    print("Classification Report:")
    print(classification_report(labels_integer_format, labels_predicted_integer_format))

In [24]:
def predict(model,normalization_type):
    evaluate(model,test_dataset,test_dataset_label,normalization_type)

In [25]:
def plot_graph(df,title,xlabel,ylabel,values=['loss'],legends=[]):
    
    for value in values:
        epoch_count = range(1, len(df.index) + 1)
        plt.plot(epoch_count, df[value].tolist())
    plt.title(title)
    plt.ylabel(ylabel)
    plt.xlabel(xlabel)
    if legends==[]:
        legends = values
    plt.legend(legends, loc='upper left')
    plt.show()

In [26]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, BatchNormalization, Dense
from tensorflow.keras.layers import AvgPool2D, GlobalAveragePooling2D, MaxPool2D
from tensorflow.keras.models import Model
from tensorflow.keras.layers import ReLU, concatenate
import tensorflow.keras.backend as K
# Creating Densenet121
def densenet(input_shape, n_classes, filters = 32):
    
    #batch norm + relu + conv
    def bn_rl_conv(x,filters,kernel=1,strides=1):
        
        x = BatchNormalization()(x)
        x = ReLU()(x)
        x = Conv2D(filters, kernel, strides=strides,padding = 'same')(x)
        return x
    
    def dense_block(x, repetition):
        
        for _ in range(repetition):
            y = bn_rl_conv(x, 4*filters)
            y = bn_rl_conv(y, filters, 3)
            x = concatenate([y,x])
        return x
        
    def transition_layer(x):
        
        x = bn_rl_conv(x, K.int_shape(x)[-1] //2 )
        x = AvgPool2D(2, strides = 2, padding = 'same')(x)
        return x
    
    input = Input (input_shape)
    x = Conv2D(64, 7, strides = 2, padding = 'same')(input)
    x = MaxPool2D(3, strides = 2, padding = 'same')(x)
    
    for repetition in [6,12,24,16]:
        
        d = dense_block(x, repetition)
        x = transition_layer(d)
    x = GlobalAveragePooling2D()(d)
    output = Dense(n_classes, activation = 'softmax')(x)
    
    model = Model(input, output)
    return model

In [27]:
x_training = np.array(x_train)
labels_training = np.array(y_train)

# Normalize the data
x_training = normalizeDataWholeSeed(x_training,normalization_type='max')
x_val_norm = normalizeDataWholeSeed(x_val,normalization_type="max")
test_dataset = normalizeDataWholeSeed(test_dataset,normalization_type='max')
    
# Extract some information
num_training = x_training.shape[0]
N_spatial = x_training.shape[1:3]
N_bands = x_training.shape[3]
batch_size = BATCH_SIZE
num_batch_per_epoch = int(num_training/batch_size)

In [28]:
import pandas as pd
import os

def save_to_csv(file_path, data_frame, header=False):
    file_exists = os.path.exists(file_path)

    if not file_exists or not header:
        data_frame.to_csv(file_path, index=False, mode='w')
    else:
        data_frame.to_csv(file_path, index=False, mode='a', header=False)

In [29]:
VARIETIES

['HD 3086', 'PBW 291', 'DBW 187', 'DBW222']

In [30]:
from tensorflow.keras import datasets, layers, models, losses, Model

In [31]:
model = None

In [32]:
start_epoch = 1

In [33]:
model_name = "DN121_"+"_IC_"+str(TRAIN_IMAGE_COUNT).zfill(5)+"_FilledArea_"+str(FILLED_AREA_RATIO)+"_BandNo_"+str(BAND_NUMBER)+"_ImageHeight_"+str(IMAGE_HEIGHT)+"_ImageWidth_"+str(IMAGE_WIDTH)+"_FILTER_"+str(FILTER)+"_FeatureExtraction_"+str(FEATURE_EXTRACTION)
if REMOVE_NOISY_BANDS:
    model_name+="_REMOVE_NOISY_BANDS_"+str(REMOVE_NOISY_BANDS)+"_NumOfBands_"+str(NUM_OF_BANDS)+"_FB_"+str(FIRST_BAND)+"_LB_"+str(LAST_BAND)
if FILTER == "savgol":
    model_name+="_WINDOW_"+str(WINDOW)+"_ORDER_"+str(ORDER)

if start_epoch != 1:
    model = tf.keras.models.load_model('./DN121models/'+str(start_epoch-1)+model_name)
else:
    input_shape = (30, 30, 168)
    num_classes = 4
    model = densenet(input_shape, num_classes)
    adam_opt = Adam(learning_rate=LEARNING_RATE_BASE, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
    model.compile(loss='sparse_categorical_crossentropy', optimizer=adam_opt, metrics=['acc'])

2024-04-08 18:37:30.696435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14684 MB memory:  -> device: 1, name: Quadro P5000, pci bus id: 0000:9b:00.0, compute capability: 6.1


In [34]:
last_epoch = 100

In [35]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 30, 30, 168)]        0         []                            
                                                                                                  
 conv2d (Conv2D)             (None, 15, 15, 64)           526912    ['input_1[0][0]']             
                                                                                                  
 max_pooling2d (MaxPooling2  (None, 8, 8, 64)             0         ['conv2d[0][0]']              
 D)                                                                                               
                                                                                                  
 batch_normalization (Batch  (None, 8, 8, 64)             256       ['max_pooling2d[0][0]']   

 )                                                                   'concatenate_2[0][0]']       
                                                                                                  
 batch_normalization_8 (Bat  (None, 8, 8, 192)            768       ['concatenate_3[0][0]']       
 chNormalization)                                                                                 
                                                                                                  
 re_lu_8 (ReLU)              (None, 8, 8, 192)            0         ['batch_normalization_8[0][0]'
                                                                    ]                             
                                                                                                  
 conv2d_9 (Conv2D)           (None, 8, 8, 128)            24704     ['re_lu_8[0][0]']             
                                                                                                  
 batch_nor

                                                                                                  
 conv2d_17 (Conv2D)          (None, 4, 4, 32)             36896     ['re_lu_16[0][0]']            
                                                                                                  
 concatenate_7 (Concatenate  (None, 4, 4, 192)            0         ['conv2d_17[0][0]',           
 )                                                                   'concatenate_6[0][0]']       
                                                                                                  
 batch_normalization_17 (Ba  (None, 4, 4, 192)            768       ['concatenate_7[0][0]']       
 tchNormalization)                                                                                
                                                                                                  
 re_lu_17 (ReLU)             (None, 4, 4, 192)            0         ['batch_normalization_17[0][0]
          

 tchNormalization)                                                                                
                                                                                                  
 re_lu_25 (ReLU)             (None, 4, 4, 320)            0         ['batch_normalization_25[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_26 (Conv2D)          (None, 4, 4, 128)            41088     ['re_lu_25[0][0]']            
                                                                                                  
 batch_normalization_26 (Ba  (None, 4, 4, 128)            512       ['conv2d_26[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 re_lu_26 

 batch_normalization_34 (Ba  (None, 4, 4, 128)            512       ['conv2d_34[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 re_lu_34 (ReLU)             (None, 4, 4, 128)            0         ['batch_normalization_34[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_35 (Conv2D)          (None, 4, 4, 32)             36896     ['re_lu_34[0][0]']            
                                                                                                  
 concatenate_16 (Concatenat  (None, 4, 4, 480)            0         ['conv2d_35[0][0]',           
 e)                                                                  'concatenate_15[0][0]']      
          

                                                                    ']                            
                                                                                                  
 conv2d_43 (Conv2D)          (None, 2, 2, 128)            41088     ['re_lu_42[0][0]']            
                                                                                                  
 batch_normalization_43 (Ba  (None, 2, 2, 128)            512       ['conv2d_43[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 re_lu_43 (ReLU)             (None, 2, 2, 128)            0         ['batch_normalization_43[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_44

 re_lu_51 (ReLU)             (None, 2, 2, 128)            0         ['batch_normalization_51[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_52 (Conv2D)          (None, 2, 2, 32)             36896     ['re_lu_51[0][0]']            
                                                                                                  
 concatenate_24 (Concatenat  (None, 2, 2, 480)            0         ['conv2d_52[0][0]',           
 e)                                                                  'concatenate_23[0][0]']      
                                                                                                  
 batch_normalization_52 (Ba  (None, 2, 2, 480)            1920      ['concatenate_24[0][0]']      
 tchNormalization)                                                                                
          

                                                                                                  
 batch_normalization_60 (Ba  (None, 2, 2, 608)            2432      ['concatenate_28[0][0]']      
 tchNormalization)                                                                                
                                                                                                  
 re_lu_60 (ReLU)             (None, 2, 2, 608)            0         ['batch_normalization_60[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_61 (Conv2D)          (None, 2, 2, 128)            77952     ['re_lu_60[0][0]']            
                                                                                                  
 batch_normalization_61 (Ba  (None, 2, 2, 128)            512       ['conv2d_61[0][0]']           
 tchNormal

 conv2d_69 (Conv2D)          (None, 2, 2, 128)            94336     ['re_lu_68[0][0]']            
                                                                                                  
 batch_normalization_69 (Ba  (None, 2, 2, 128)            512       ['conv2d_69[0][0]']           
 tchNormalization)                                                                                
                                                                                                  
 re_lu_69 (ReLU)             (None, 2, 2, 128)            0         ['batch_normalization_69[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_70 (Conv2D)          (None, 2, 2, 32)             36896     ['re_lu_69[0][0]']            
                                                                                                  
 concatena

                                                                                                  
 conv2d_78 (Conv2D)          (None, 2, 2, 32)             36896     ['re_lu_77[0][0]']            
                                                                                                  
 concatenate_37 (Concatenat  (None, 2, 2, 896)            0         ['conv2d_78[0][0]',           
 e)                                                                  'concatenate_36[0][0]']      
                                                                                                  
 batch_normalization_78 (Ba  (None, 2, 2, 896)            3584      ['concatenate_37[0][0]']      
 tchNormalization)                                                                                
                                                                                                  
 re_lu_78 (ReLU)             (None, 2, 2, 896)            0         ['batch_normalization_78[0][0]
          

 tchNormalization)                                                                                
                                                                                                  
 re_lu_86 (ReLU)             (None, 2, 2, 1024)           0         ['batch_normalization_86[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_87 (Conv2D)          (None, 2, 2, 512)            524800    ['re_lu_86[0][0]']            
                                                                                                  
 average_pooling2d_2 (Avera  (None, 1, 1, 512)            0         ['conv2d_87[0][0]']           
 gePooling2D)                                                                                     
                                                                                                  
 batch_nor

 concatenate_45 (Concatenat  (None, 1, 1, 640)            0         ['conv2d_95[0][0]',           
 e)                                                                  'concatenate_44[0][0]']      
                                                                                                  
 batch_normalization_95 (Ba  (None, 1, 1, 640)            2560      ['concatenate_45[0][0]']      
 tchNormalization)                                                                                
                                                                                                  
 re_lu_95 (ReLU)             (None, 1, 1, 640)            0         ['batch_normalization_95[0][0]
                                                                    ']                            
                                                                                                  
 conv2d_96 (Conv2D)          (None, 1, 1, 128)            82048     ['re_lu_95[0][0]']            
          

                                                                    ]']                           
                                                                                                  
 conv2d_104 (Conv2D)         (None, 1, 1, 128)            98432     ['re_lu_103[0][0]']           
                                                                                                  
 batch_normalization_104 (B  (None, 1, 1, 128)            512       ['conv2d_104[0][0]']          
 atchNormalization)                                                                               
                                                                                                  
 re_lu_104 (ReLU)            (None, 1, 1, 128)            0         ['batch_normalization_104[0][0
                                                                    ]']                           
                                                                                                  
 conv2d_10

 re_lu_112 (ReLU)            (None, 1, 1, 128)            0         ['batch_normalization_112[0][0
                                                                    ]']                           
                                                                                                  
 conv2d_113 (Conv2D)         (None, 1, 1, 32)             36896     ['re_lu_112[0][0]']           
                                                                                                  
 concatenate_54 (Concatenat  (None, 1, 1, 928)            0         ['conv2d_113[0][0]',          
 e)                                                                  'concatenate_53[0][0]']      
                                                                                                  
 batch_normalization_113 (B  (None, 1, 1, 928)            3712      ['concatenate_54[0][0]']      
 atchNormalization)                                                                               
          

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

tic = start_timer()
while start_epoch<=last_epoch:
    print("\nEpoch: ",start_epoch)
    history = model.fit(x_training, labels_training, batch_size=batch_size, epochs = 1, validation_data=(x_val_norm, y_val), verbose=2)
    model.save('./DN121models/'+str(start_epoch)+model_name)
    print("Model saved on epoch: ",start_epoch)
    
    history_dataframe = pd.DataFrame.from_dict(history.history)
    save_to_csv('./csvs/'+model_name+'.csv', history_dataframe, header=True)
    print("added to csv")
    
    y_pred = model.predict(test_dataset)

    y_pred_label = np.argmax(y_pred, axis=1)

    # Calculate accuracy
    accuracy = accuracy_score(test_dataset_label, y_pred_label)
    print("Accuracy:", accuracy)

    # Calculate confusion matrix
    cm = confusion_matrix(test_dataset_label, y_pred_label)
    print("Confusion Matrix:")
    print(cm)

    # Calculate precision, recall, and F1-score for each class
    print("Classification Report:")
    print(classification_report(test_dataset_label, y_pred_label))
    start_epoch+=1
    
toc = end_timer()
show_time(tic,toc)


Testing started

Epoch:  1


2024-04-08 18:39:09.397190: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8907
2024-04-08 18:39:12.355362: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x77d3b2a4b090 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-04-08 18:39:12.355433: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro P5000, Compute Capability 6.1
2024-04-08 18:39:14.075975: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:255] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-04-08 18:39:20.661838: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


600/600 - 273s - loss: 1.1006 - acc: 0.5073 - val_loss: 2.6301 - val_acc: 0.2781 - 273s/epoch - 455ms/step
INFO:tensorflow:Assets written to: ./DN121models/1DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/1DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  1
added to csv
50/50 [==============================] - 8s 33ms/step
Accuracy: 0.285625
Confusion Matrix:
[[ 28   0 370   2]
 [  1  23 376   0]
 [  0   3 397   0]
 [  3   0 388   9]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.07      0.13       400
           1       0.88      0.06      0.11       400
           2       0.26      0.99      0.41       400
           3       0.82      0.02      0.04       400

    accuracy                           0.29      1600
   macro avg       0.71      0.29      0.17      1600
weighted avg       0.71      0.29      0.17      1600


Epoch:  2
600/600 - 91s - loss: 0.7968 - acc: 0.6715 - val_loss: 1.1315 - val_acc: 0.5500 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/2DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/2DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  2
added to csv
50/50 [==============================] - 2s 34ms/step
Accuracy: 0.54625
Confusion Matrix:
[[116  26 257   1]
 [  9 220 170   1]
 [  2  35 363   0]
 [ 22  68 135 175]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.29      0.42       400
           1       0.63      0.55      0.59       400
           2       0.39      0.91      0.55       400
           3       0.99      0.44      0.61       400

    accuracy                           0.55      1600
   macro avg       0.70      0.55      0.54      1600
weighted avg       0.70      0.55      0.54      1600


Epoch:  3
600/600 - 92s - loss: 0.6318 - acc: 0.7490 - val_loss: 0.8383 - val_acc: 0.7044 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/3DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/3DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  3
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.681875
Confusion Matrix:
[[108  83 101 108]
 [  7 299  35  59]
 [  4  90 284  22]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.27      0.42       400
           1       0.63      0.75      0.69       400
           2       0.68      0.71      0.69       400
           3       0.68      1.00      0.81       400

    accuracy                           0.68      1600
   macro avg       0.72      0.68      0.65      1600
weighted avg       0.72      0.68      0.65      1600


Epoch:  4
600/600 - 92s - loss: 0.4780 - acc: 0.8123 - val_loss: 1.4909 - val_acc: 0.5150 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/4DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/4DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  4
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.51125
Confusion Matrix:
[[ 77   8 315   0]
 [  2 162 236   0]
 [  0   6 394   0]
 [ 11  22 182 185]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.19      0.31       400
           1       0.82      0.41      0.54       400
           2       0.35      0.98      0.52       400
           3       1.00      0.46      0.63       400

    accuracy                           0.51      1600
   macro avg       0.76      0.51      0.50      1600
weighted avg       0.76      0.51      0.50      1600


Epoch:  5
600/600 - 91s - loss: 0.3110 - acc: 0.8885 - val_loss: 0.5889 - val_acc: 0.8037 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/5DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/5DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  5
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.746875
Confusion Matrix:
[[247  48 105   0]
 [ 34 317  49   0]
 [ 12  71 317   0]
 [ 44  23  19 314]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.62      0.67       400
           1       0.69      0.79      0.74       400
           2       0.65      0.79      0.71       400
           3       1.00      0.79      0.88       400

    accuracy                           0.75      1600
   macro avg       0.77      0.75      0.75      1600
weighted avg       0.77      0.75      0.75      1600


Epoch:  6
600/600 - 91s - loss: 0.1975 - acc: 0.9269 - val_loss: 0.6392 - val_acc: 0.8181 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/6DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/6DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  6
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.775625
Confusion Matrix:
[[214 134  50   2]
 [  8 366  26   0]
 [ 11 117 272   0]
 [  7   4   0 389]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.54      0.67       400
           1       0.59      0.92      0.72       400
           2       0.78      0.68      0.73       400
           3       0.99      0.97      0.98       400

    accuracy                           0.78      1600
   macro avg       0.81      0.78      0.77      1600
weighted avg       0.81      0.78      0.77      1600


Epoch:  7
600/600 - 98s - loss: 0.1406 - acc: 0.9498 - val_loss: 0.6003 - val_acc: 0.8250 - 98s/epoch - 164ms/step
INFO:tensorflow:Assets written to: ./DN121models/7DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/7DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  7
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.773125
Confusion Matrix:
[[216  86  98   0]
 [ 13 363  24   0]
 [  7 108 285   0]
 [  8   9  10 373]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.54      0.67       400
           1       0.64      0.91      0.75       400
           2       0.68      0.71      0.70       400
           3       1.00      0.93      0.97       400

    accuracy                           0.77      1600
   macro avg       0.80      0.77      0.77      1600
weighted avg       0.80      0.77      0.77      1600


Epoch:  8
600/600 - 91s - loss: 0.1148 - acc: 0.9598 - val_loss: 1.4816 - val_acc: 0.6581 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/8DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/8DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  8
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.5825
Confusion Matrix:
[[225  66 109   0]
 [ 25 360  15   0]
 [  8 134 258   0]
 [101  73 137  89]]
Classification Report:
              precision    recall  f1-score   support

           0       0.63      0.56      0.59       400
           1       0.57      0.90      0.70       400
           2       0.50      0.65      0.56       400
           3       1.00      0.22      0.36       400

    accuracy                           0.58      1600
   macro avg       0.67      0.58      0.55      1600
weighted avg       0.67      0.58      0.55      1600


Epoch:  9
600/600 - 92s - loss: 0.1023 - acc: 0.9646 - val_loss: 0.7365 - val_acc: 0.8087 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/9DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/9DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  9
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.809375
Confusion Matrix:
[[275  25 100   0]
 [ 45 293  62   0]
 [ 16  16 368   0]
 [ 30   0  11 359]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.69      0.72       400
           1       0.88      0.73      0.80       400
           2       0.68      0.92      0.78       400
           3       1.00      0.90      0.95       400

    accuracy                           0.81      1600
   macro avg       0.83      0.81      0.81      1600
weighted avg       0.83      0.81      0.81      1600


Epoch:  10
600/600 - 91s - loss: 0.0917 - acc: 0.9681 - val_loss: 1.0533 - val_acc: 0.7700 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/10DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/10DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  10
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.80375
Confusion Matrix:
[[363  13  24   0]
 [116 256  28   0]
 [ 76  36 288   0]
 [ 18   3   0 379]]
Classification Report:
              precision    recall  f1-score   support

           0       0.63      0.91      0.75       400
           1       0.83      0.64      0.72       400
           2       0.85      0.72      0.78       400
           3       1.00      0.95      0.97       400

    accuracy                           0.80      1600
   macro avg       0.83      0.80      0.81      1600
weighted avg       0.83      0.80      0.81      1600


Epoch:  11
600/600 - 91s - loss: 0.0959 - acc: 0.9652 - val_loss: 1.1767 - val_acc: 0.7469 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/11DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/11DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  11
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.735
Confusion Matrix:
[[259  29 112   0]
 [ 35 309  56   0]
 [ 10  29 361   0]
 [ 93   3  57 247]]
Classification Report:
              precision    recall  f1-score   support

           0       0.65      0.65      0.65       400
           1       0.84      0.77      0.80       400
           2       0.62      0.90      0.73       400
           3       1.00      0.62      0.76       400

    accuracy                           0.73      1600
   macro avg       0.78      0.73      0.74      1600
weighted avg       0.78      0.73      0.74      1600


Epoch:  12
600/600 - 91s - loss: 0.0831 - acc: 0.9729 - val_loss: 0.5313 - val_acc: 0.8656 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/12DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/12DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  12
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.844375
Confusion Matrix:
[[256  59  85   0]
 [ 19 367  14   0]
 [ 11  58 331   0]
 [  1   0   2 397]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.64      0.75       400
           1       0.76      0.92      0.83       400
           2       0.77      0.83      0.80       400
           3       1.00      0.99      1.00       400

    accuracy                           0.84      1600
   macro avg       0.85      0.84      0.84      1600
weighted avg       0.85      0.84      0.84      1600


Epoch:  13
600/600 - 91s - loss: 0.0425 - acc: 0.9860 - val_loss: 1.0950 - val_acc: 0.7994 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/13DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/13DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  13
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.769375
Confusion Matrix:
[[242  45 113   0]
 [ 22 348  30   0]
 [  8  44 348   0]
 [ 87   1  19 293]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.60      0.64       400
           1       0.79      0.87      0.83       400
           2       0.68      0.87      0.76       400
           3       1.00      0.73      0.85       400

    accuracy                           0.77      1600
   macro avg       0.79      0.77      0.77      1600
weighted avg       0.79      0.77      0.77      1600


Epoch:  14
600/600 - 91s - loss: 0.0909 - acc: 0.9706 - val_loss: 0.5812 - val_acc: 0.8606 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/14DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/14DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  14
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.82
Confusion Matrix:
[[255  45 100   0]
 [ 29 348  23   0]
 [ 14  38 348   0]
 [ 27   0  12 361]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70       400
           1       0.81      0.87      0.84       400
           2       0.72      0.87      0.79       400
           3       1.00      0.90      0.95       400

    accuracy                           0.82      1600
   macro avg       0.83      0.82      0.82      1600
weighted avg       0.83      0.82      0.82      1600


Epoch:  15
600/600 - 91s - loss: 0.0660 - acc: 0.9792 - val_loss: 0.6438 - val_acc: 0.8562 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/15DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/15DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  15
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.848125
Confusion Matrix:
[[283  42  75   0]
 [ 33 331  35   1]
 [ 13  36 349   2]
 [  6   0   0 394]]
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.71      0.77       400
           1       0.81      0.83      0.82       400
           2       0.76      0.87      0.81       400
           3       0.99      0.98      0.99       400

    accuracy                           0.85      1600
   macro avg       0.85      0.85      0.85      1600
weighted avg       0.85      0.85      0.85      1600


Epoch:  16
600/600 - 91s - loss: 0.0426 - acc: 0.9871 - val_loss: 0.6490 - val_acc: 0.8712 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/16DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/16DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  16
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.801875
Confusion Matrix:
[[168 153  79   0]
 [  2 387  11   0]
 [  5  67 328   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.42      0.58       400
           1       0.64      0.97      0.77       400
           2       0.78      0.82      0.80       400
           3       1.00      1.00      1.00       400

    accuracy                           0.80      1600
   macro avg       0.85      0.80      0.79      1600
weighted avg       0.85      0.80      0.79      1600


Epoch:  17
600/600 - 91s - loss: 0.0693 - acc: 0.9750 - val_loss: 0.6668 - val_acc: 0.8587 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/17DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/17DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  17
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.806875
Confusion Matrix:
[[185  21 194   0]
 [ 26 317  57   0]
 [  0  11 389   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.46      0.61       400
           1       0.91      0.79      0.85       400
           2       0.61      0.97      0.75       400
           3       1.00      1.00      1.00       400

    accuracy                           0.81      1600
   macro avg       0.85      0.81      0.80      1600
weighted avg       0.85      0.81      0.80      1600


Epoch:  18
600/600 - 91s - loss: 0.0580 - acc: 0.9796 - val_loss: 0.7097 - val_acc: 0.8400 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/18DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/18DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  18
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.8325
Confusion Matrix:
[[234  34 110  22]
 [ 17 326  53   4]
 [  9  14 372   5]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.58      0.71       400
           1       0.87      0.81      0.84       400
           2       0.70      0.93      0.80       400
           3       0.93      1.00      0.96       400

    accuracy                           0.83      1600
   macro avg       0.85      0.83      0.83      1600
weighted avg       0.85      0.83      0.83      1600


Epoch:  19
600/600 - 91s - loss: 0.0609 - acc: 0.9810 - val_loss: 0.8978 - val_acc: 0.8469 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/19DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/19DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  19
added to csv
50/50 [==============================] - 2s 30ms/step
Accuracy: 0.848125
Confusion Matrix:
[[313  69  18   0]
 [ 22 369   9   0]
 [ 52  73 275   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.78      0.80       400
           1       0.72      0.92      0.81       400
           2       0.91      0.69      0.78       400
           3       1.00      1.00      1.00       400

    accuracy                           0.85      1600
   macro avg       0.86      0.85      0.85      1600
weighted avg       0.86      0.85      0.85      1600


Epoch:  20
600/600 - 90s - loss: 0.0267 - acc: 0.9921 - val_loss: 0.8691 - val_acc: 0.8313 - 90s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/20DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/20DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  20
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.82125
Confusion Matrix:
[[305  54  41   0]
 [ 36 351  13   0]
 [ 27  64 309   0]
 [ 39   2  10 349]]
Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.76      0.76       400
           1       0.75      0.88      0.81       400
           2       0.83      0.77      0.80       400
           3       1.00      0.87      0.93       400

    accuracy                           0.82      1600
   macro avg       0.83      0.82      0.82      1600
weighted avg       0.83      0.82      0.82      1600


Epoch:  21
600/600 - 91s - loss: 0.0239 - acc: 0.9927 - val_loss: 0.9975 - val_acc: 0.8325 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/21DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/21DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  21
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.78625
Confusion Matrix:
[[229 148  23   0]
 [  3 392   4   1]
 [ 13 148 238   1]
 [  1   0   0 399]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.57      0.71       400
           1       0.57      0.98      0.72       400
           2       0.90      0.59      0.72       400
           3       1.00      1.00      1.00       400

    accuracy                           0.79      1600
   macro avg       0.85      0.79      0.79      1600
weighted avg       0.85      0.79      0.79      1600


Epoch:  22
600/600 - 91s - loss: 0.1049 - acc: 0.9671 - val_loss: 5.3871 - val_acc: 0.5894 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/22DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/22DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  22
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.606875
Confusion Matrix:
[[  7  28  36 329]
 [  2 272  21 105]
 [  0  11 292  97]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.02      0.03       400
           1       0.87      0.68      0.77       400
           2       0.84      0.73      0.78       400
           3       0.43      1.00      0.60       400

    accuracy                           0.61      1600
   macro avg       0.73      0.61      0.55      1600
weighted avg       0.73      0.61      0.55      1600


Epoch:  23
600/600 - 91s - loss: 0.0427 - acc: 0.9846 - val_loss: 0.6194 - val_acc: 0.8619 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/23DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/23DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  23
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.815625
Confusion Matrix:
[[197  51 144   8]
 [ 28 334  38   0]
 [  4  21 374   1]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.49      0.63       400
           1       0.82      0.83      0.83       400
           2       0.67      0.94      0.78       400
           3       0.98      1.00      0.99       400

    accuracy                           0.82      1600
   macro avg       0.83      0.82      0.81      1600
weighted avg       0.83      0.82      0.81      1600


Epoch:  24
600/600 - 90s - loss: 0.0126 - acc: 0.9962 - val_loss: 0.5275 - val_acc: 0.9006 - 90s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/24DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/24DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  24
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.855
Confusion Matrix:
[[240  53 106   1]
 [ 12 369  19   0]
 [ 10  31 359   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.60      0.73       400
           1       0.81      0.92      0.87       400
           2       0.74      0.90      0.81       400
           3       1.00      1.00      1.00       400

    accuracy                           0.85      1600
   macro avg       0.87      0.85      0.85      1600
weighted avg       0.87      0.85      0.85      1600


Epoch:  25
600/600 - 91s - loss: 0.0133 - acc: 0.9956 - val_loss: 0.7945 - val_acc: 0.8519 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/25DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/25DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  25
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.83
Confusion Matrix:
[[247  16 135   2]
 [ 23 302  75   0]
 [ 17   3 379   1]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.62      0.72       400
           1       0.94      0.76      0.84       400
           2       0.64      0.95      0.77       400
           3       0.99      1.00      1.00       400

    accuracy                           0.83      1600
   macro avg       0.86      0.83      0.83      1600
weighted avg       0.86      0.83      0.83      1600


Epoch:  26
600/600 - 90s - loss: 0.0838 - acc: 0.9715 - val_loss: 0.6498 - val_acc: 0.8550 - 90s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/26DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/26DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  26
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.824375
Confusion Matrix:
[[246 109  45   0]
 [  3 391   6   0]
 [ 18  86 296   0]
 [ 13   0   1 386]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.61      0.72       400
           1       0.67      0.98      0.79       400
           2       0.85      0.74      0.79       400
           3       1.00      0.96      0.98       400

    accuracy                           0.82      1600
   macro avg       0.85      0.82      0.82      1600
weighted avg       0.85      0.82      0.82      1600


Epoch:  27
600/600 - 91s - loss: 0.0314 - acc: 0.9883 - val_loss: 0.6168 - val_acc: 0.8856 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/27DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/27DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  27
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.835625
Confusion Matrix:
[[240 115  45   0]
 [  5 387   8   0]
 [ 12  75 313   0]
 [  3   0   0 397]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.60      0.73       400
           1       0.67      0.97      0.79       400
           2       0.86      0.78      0.82       400
           3       1.00      0.99      1.00       400

    accuracy                           0.84      1600
   macro avg       0.86      0.84      0.83      1600
weighted avg       0.86      0.84      0.83      1600


Epoch:  28
600/600 - 91s - loss: 0.0061 - acc: 0.9981 - val_loss: 0.5515 - val_acc: 0.8975 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/28DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/28DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  28
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.85875
Confusion Matrix:
[[264  48  88   0]
 [ 18 360  22   0]
 [ 14  36 350   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.66      0.76       400
           1       0.81      0.90      0.85       400
           2       0.76      0.88      0.81       400
           3       1.00      1.00      1.00       400

    accuracy                           0.86      1600
   macro avg       0.87      0.86      0.86      1600
weighted avg       0.87      0.86      0.86      1600


Epoch:  29
600/600 - 92s - loss: 0.0372 - acc: 0.9902 - val_loss: 1.8178 - val_acc: 0.7306 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/29DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/29DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  29
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.74625
Confusion Matrix:
[[330  58  12   0]
 [ 58 338   4   0]
 [ 47  99 254   0]
 [ 91  32   5 272]]
Classification Report:
              precision    recall  f1-score   support

           0       0.63      0.82      0.71       400
           1       0.64      0.84      0.73       400
           2       0.92      0.64      0.75       400
           3       1.00      0.68      0.81       400

    accuracy                           0.75      1600
   macro avg       0.80      0.75      0.75      1600
weighted avg       0.80      0.75      0.75      1600


Epoch:  30
600/600 - 91s - loss: 0.0700 - acc: 0.9756 - val_loss: 0.6576 - val_acc: 0.8769 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/30DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/30DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  30
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.8425
Confusion Matrix:
[[243 112  43   2]
 [  5 381  14   0]
 [ 13  59 324   4]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.61      0.74       400
           1       0.69      0.95      0.80       400
           2       0.85      0.81      0.83       400
           3       0.99      1.00      0.99       400

    accuracy                           0.84      1600
   macro avg       0.86      0.84      0.84      1600
weighted avg       0.86      0.84      0.84      1600


Epoch:  31
600/600 - 91s - loss: 0.0159 - acc: 0.9952 - val_loss: 0.6692 - val_acc: 0.8875 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/31DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/31DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  31
added to csv
50/50 [==============================] - 2s 34ms/step
Accuracy: 0.849375
Confusion Matrix:
[[261  49  90   0]
 [ 30 352  18   0]
 [  9  44 347   0]
 [  1   0   0 399]]
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.65      0.74       400
           1       0.79      0.88      0.83       400
           2       0.76      0.87      0.81       400
           3       1.00      1.00      1.00       400

    accuracy                           0.85      1600
   macro avg       0.86      0.85      0.85      1600
weighted avg       0.86      0.85      0.85      1600


Epoch:  32
600/600 - 92s - loss: 0.0261 - acc: 0.9931 - val_loss: 6.2576 - val_acc: 0.5150 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/32DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/32DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  32
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.4725
Confusion Matrix:
[[213 183   4   0]
 [  7 393   0   0]
 [ 52 199 149   0]
 [196 194   9   1]]
Classification Report:
              precision    recall  f1-score   support

           0       0.46      0.53      0.49       400
           1       0.41      0.98      0.57       400
           2       0.92      0.37      0.53       400
           3       1.00      0.00      0.00       400

    accuracy                           0.47      1600
   macro avg       0.70      0.47      0.40      1600
weighted avg       0.70      0.47      0.40      1600


Epoch:  33
600/600 - 92s - loss: 0.0400 - acc: 0.9873 - val_loss: 0.5764 - val_acc: 0.8931 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/33DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/33DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  33
added to csv
50/50 [==============================] - 1s 29ms/step
Accuracy: 0.866875
Confusion Matrix:
[[262  37 101   0]
 [ 18 349  33   0]
 [  9  14 377   0]
 [  1   0   0 399]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.66      0.76       400
           1       0.87      0.87      0.87       400
           2       0.74      0.94      0.83       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.86      1600
weighted avg       0.88      0.87      0.86      1600


Epoch:  34
600/600 - 91s - loss: 0.0386 - acc: 0.9885 - val_loss: 0.5281 - val_acc: 0.9019 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/34DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/34DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  34
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.849375
Confusion Matrix:
[[238  71  91   0]
 [ 15 370  15   0]
 [  6  42 352   0]
 [  0   0   1 399]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.59      0.72       400
           1       0.77      0.93      0.84       400
           2       0.77      0.88      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.85      1600
   macro avg       0.86      0.85      0.84      1600
weighted avg       0.86      0.85      0.84      1600


Epoch:  35
600/600 - 91s - loss: 0.0231 - acc: 0.9906 - val_loss: 0.8502 - val_acc: 0.8431 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/35DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/35DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  35
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.8275
Confusion Matrix:
[[306  27  67   0]
 [ 28 357  15   0]
 [ 17  48 335   0]
 [ 50   0  24 326]]
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.77      0.76       400
           1       0.83      0.89      0.86       400
           2       0.76      0.84      0.80       400
           3       1.00      0.81      0.90       400

    accuracy                           0.83      1600
   macro avg       0.84      0.83      0.83      1600
weighted avg       0.84      0.83      0.83      1600


Epoch:  36
600/600 - 90s - loss: 0.0116 - acc: 0.9946 - val_loss: 0.7530 - val_acc: 0.8769 - 90s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/36DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/36DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  36
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.819375
Confusion Matrix:
[[211 138  51   0]
 [  1 391   8   0]
 [ 12  79 309   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.53      0.68       400
           1       0.64      0.98      0.78       400
           2       0.84      0.77      0.80       400
           3       1.00      1.00      1.00       400

    accuracy                           0.82      1600
   macro avg       0.86      0.82      0.81      1600
weighted avg       0.86      0.82      0.81      1600


Epoch:  37
600/600 - 92s - loss: 0.0603 - acc: 0.9798 - val_loss: 0.9594 - val_acc: 0.8487 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/37DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/37DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  37
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.81625
Confusion Matrix:
[[214  47 139   0]
 [ 15 361  24   0]
 [  4  15 381   0]
 [ 39   1  10 350]]
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.54      0.64       400
           1       0.85      0.90      0.88       400
           2       0.69      0.95      0.80       400
           3       1.00      0.88      0.93       400

    accuracy                           0.82      1600
   macro avg       0.83      0.82      0.81      1600
weighted avg       0.83      0.82      0.81      1600


Epoch:  38
600/600 - 91s - loss: 0.0265 - acc: 0.9906 - val_loss: 0.6420 - val_acc: 0.8781 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/38DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/38DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  38
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.8575
Confusion Matrix:
[[291  53  56   0]
 [ 16 370  14   0]
 [ 20  68 312   0]
 [  1   0   0 399]]
Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.73      0.80       400
           1       0.75      0.93      0.83       400
           2       0.82      0.78      0.80       400
           3       1.00      1.00      1.00       400

    accuracy                           0.86      1600
   macro avg       0.86      0.86      0.86      1600
weighted avg       0.86      0.86      0.86      1600


Epoch:  39
600/600 - 90s - loss: 0.0031 - acc: 0.9994 - val_loss: 0.5452 - val_acc: 0.9106 - 90s/epoch - 150ms/step
INFO:tensorflow:Assets written to: ./DN121models/39DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/39DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  39
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.866875
Confusion Matrix:
[[236  36 128   0]
 [  8 373  19   0]
 [  4  17 378   1]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.59      0.73       400
           1       0.88      0.93      0.90       400
           2       0.72      0.94      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.89      0.87      0.86      1600
weighted avg       0.89      0.87      0.86      1600


Epoch:  40
600/600 - 91s - loss: 2.9629e-04 - acc: 1.0000 - val_loss: 0.5405 - val_acc: 0.9187 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/40DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/40DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  40
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.8675
Confusion Matrix:
[[248  37 115   0]
 [ 10 376  14   0]
 [  9  27 364   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.85      0.94      0.90       400
           2       0.74      0.91      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.86      1600
weighted avg       0.88      0.87      0.86      1600


Epoch:  41
600/600 - 90s - loss: 8.5599e-05 - acc: 1.0000 - val_loss: 0.5454 - val_acc: 0.9181 - 90s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/41DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/41DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  41
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.866875
Confusion Matrix:
[[248  38 114   0]
 [  9 376  15   0]
 [ 10  27 363   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.85      0.94      0.89       400
           2       0.74      0.91      0.81       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.86      1600
weighted avg       0.88      0.87      0.86      1600


Epoch:  42
600/600 - 91s - loss: 6.1021e-05 - acc: 1.0000 - val_loss: 0.5519 - val_acc: 0.9181 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/42DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/42DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  42
added to csv
50/50 [==============================] - 2s 30ms/step
Accuracy: 0.8675
Confusion Matrix:
[[249  38 113   0]
 [  9 375  16   0]
 [ 10  26 364   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.75       400
           1       0.85      0.94      0.89       400
           2       0.74      0.91      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.86      1600
weighted avg       0.88      0.87      0.86      1600


Epoch:  43
600/600 - 90s - loss: 4.6390e-05 - acc: 1.0000 - val_loss: 0.5591 - val_acc: 0.9169 - 90s/epoch - 150ms/step
INFO:tensorflow:Assets written to: ./DN121models/43DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/43DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  43
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.87
Confusion Matrix:
[[248  38 114   0]
 [  9 376  15   0]
 [ 10  22 368   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.86      0.94      0.90       400
           2       0.74      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  44
600/600 - 91s - loss: 3.5791e-05 - acc: 1.0000 - val_loss: 0.5668 - val_acc: 0.9162 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/44DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/44DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  44
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.87
Confusion Matrix:
[[248  38 114   0]
 [  9 376  15   0]
 [ 10  22 368   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.86      0.94      0.90       400
           2       0.74      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  45
600/600 - 91s - loss: 2.7684e-05 - acc: 1.0000 - val_loss: 0.5750 - val_acc: 0.9162 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/45DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/45DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  45
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.87125
Confusion Matrix:
[[248  38 114   0]
 [  9 376  15   0]
 [  9  21 370   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.86      0.94      0.90       400
           2       0.74      0.93      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  46
600/600 - 91s - loss: 2.1373e-05 - acc: 1.0000 - val_loss: 0.5838 - val_acc: 0.9162 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/46DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/46DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  46
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.871875
Confusion Matrix:
[[249  38 113   0]
 [  9 376  15   0]
 [  9  21 370   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.75       400
           1       0.86      0.94      0.90       400
           2       0.74      0.93      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  47
600/600 - 91s - loss: 1.6430e-05 - acc: 1.0000 - val_loss: 0.5929 - val_acc: 0.9162 - 91s/epoch - 151ms/step
INFO:tensorflow:Assets written to: ./DN121models/47DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/47DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  47
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.871875
Confusion Matrix:
[[249  38 113   0]
 [  9 376  15   0]
 [  9  21 370   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.75       400
           1       0.86      0.94      0.90       400
           2       0.74      0.93      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  48
600/600 - 91s - loss: 1.2559e-05 - acc: 1.0000 - val_loss: 0.6024 - val_acc: 0.9162 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/48DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/48DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  48
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.87
Confusion Matrix:
[[248  38 114   0]
 [  9 375  16   0]
 [ 10  21 369   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.86      0.94      0.90       400
           2       0.74      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  49
600/600 - 91s - loss: 9.5482e-06 - acc: 1.0000 - val_loss: 0.6123 - val_acc: 0.9169 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/49DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/49DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  49
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.87
Confusion Matrix:
[[248  37 115   0]
 [  9 375  16   0]
 [ 10  21 369   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.87      0.94      0.90       400
           2       0.74      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  50
600/600 - 92s - loss: 7.2192e-06 - acc: 1.0000 - val_loss: 0.6225 - val_acc: 0.9169 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/50DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/50DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  50
added to csv
50/50 [==============================] - 2s 33ms/step
Accuracy: 0.87
Confusion Matrix:
[[248  37 115   0]
 [  9 375  16   0]
 [ 10  21 369   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.87      0.94      0.90       400
           2       0.74      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  51
600/600 - 91s - loss: 5.4311e-06 - acc: 1.0000 - val_loss: 0.6329 - val_acc: 0.9175 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/51DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/51DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  51
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.869375
Confusion Matrix:
[[247  36 117   0]
 [  9 375  16   0]
 [ 10  21 369   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.87      0.94      0.90       400
           2       0.74      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  52
600/600 - 92s - loss: 4.0666e-06 - acc: 1.0000 - val_loss: 0.6436 - val_acc: 0.9175 - 92s/epoch - 153ms/step
INFO:tensorflow:Assets written to: ./DN121models/52DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/52DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  52
added to csv
50/50 [==============================] - 2s 32ms/step
Accuracy: 0.86875
Confusion Matrix:
[[247  35 118   0]
 [  9 375  16   0]
 [ 10  22 368   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.87      0.94      0.90       400
           2       0.73      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.86      1600
weighted avg       0.88      0.87      0.86      1600


Epoch:  53
600/600 - 90s - loss: 3.0334e-06 - acc: 1.0000 - val_loss: 0.6545 - val_acc: 0.9175 - 90s/epoch - 150ms/step
INFO:tensorflow:Assets written to: ./DN121models/53DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/53DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  53
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.86875
Confusion Matrix:
[[247  35 118   0]
 [  9 375  16   0]
 [ 10  22 368   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.62      0.74       400
           1       0.87      0.94      0.90       400
           2       0.73      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.86      1600
weighted avg       0.88      0.87      0.86      1600


Epoch:  54
600/600 - 91s - loss: 2.2558e-06 - acc: 1.0000 - val_loss: 0.6656 - val_acc: 0.9175 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/54DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/54DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  54
added to csv
50/50 [==============================] - 2s 31ms/step
Accuracy: 0.869375
Confusion Matrix:
[[246  35 119   0]
 [  8 376  16   0]
 [ 10  21 369   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.61      0.74       400
           1       0.87      0.94      0.90       400
           2       0.73      0.92      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  55
600/600 - 91s - loss: 1.6714e-06 - acc: 1.0000 - val_loss: 0.6770 - val_acc: 0.9181 - 91s/epoch - 152ms/step
INFO:tensorflow:Assets written to: ./DN121models/55DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


INFO:tensorflow:Assets written to: ./DN121models/55DN121__IC_01200_FilledArea_0.9_BandNo_60_ImageHeight_30_ImageWidth_30_FILTER_msc_FeatureExtraction_none/assets


Model saved on epoch:  55
added to csv
50/50 [==============================] - 2s 30ms/step
Accuracy: 0.87
Confusion Matrix:
[[245  36 119   0]
 [  8 376  16   0]
 [ 10  19 371   0]
 [  0   0   0 400]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.61      0.74       400
           1       0.87      0.94      0.90       400
           2       0.73      0.93      0.82       400
           3       1.00      1.00      1.00       400

    accuracy                           0.87      1600
   macro avg       0.88      0.87      0.87      1600
weighted avg       0.88      0.87      0.87      1600


Epoch:  56


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(test_dataset)

y_pred_label = np.argmax(y_pred, axis=1)

# Calculate accuracy
accuracy = accuracy_score(test_dataset_label, y_pred_label)
print("Accuracy:", accuracy)

# Calculate confusion matrix
cm = confusion_matrix(test_dataset_label, y_pred_label)
print("Confusion Matrix:")
print(cm)

# Calculate precision, recall, and F1-score for each class
print("Classification Report:")
print(classification_report(test_dataset_label, y_pred_label))

In [ ]:
df_cm = pd.DataFrame(cm,index =[i for i in VARIETIES],columns=[i for i in VARIETIES])
sn.heatmap(df_cm, annot=True, annot_kws={"size": 16},fmt='.0f') # font size

plt.show()